#!/bin/sh
HERE=$(dirname "$0")
python $HERE/import-feeds.py
python $HERE/render.py $HERE/templates/config.ini > $HERE/out/config.ini
cp $HERE/out/config.ini /home/gleitz/projects/planet-nightly/examples/wabi-sabi/config.ini

# TODO(gleitz): re-enable when there is a website
# python $HERE/update-participants.py
